language: objective-c
osx_image: xcode9.2
rvm:
- 2.2
before_install:
- chmod a+x ./Reabilitacao-Motora/Assets/Scripts/travis_install.sh
- chmod a+x ./Reabilitacao-Motora/Assets/Scripts/travis_build.sh
install:
- ./Reabilitacao-Motora/Assets/Scripts/travis_install.sh
script:
- ./Reabilitacao-Motora/Assets/Scripts/travis_build.sh